# Generated by Django 5.2.3 on 2025-06-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('volunteer_id', models.AutoField(primary_key=True, serialize=False)),
                ('volunteer_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')])),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('bio', models.CharField(blank=True, max_length=225)),
                ('expertise', models.CharField(choices=[(1, 'depression'), (2, 'anxiety'), (3, 'stress management'), (4, 'grief & loss'), (5, 'self-esteem issues'), (6, 'relationship problems'), (7, 'family issues'), (8, 'loneliness'), (9, 'academic pressure'), (10, 'addiction support'), (11, 'anger management'), (12, 'workplace stress'), (13, '')])),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
        ),
    ]
