# Generated by Django 5.2.3 on 2025-06-21 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('ChatMessage_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.PositiveIntegerField()),
                ('message_text', models.TextField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
            ],
        ),
    ]
